### PR TITLE
pkg/naming: fix LabelValuesByName rendering

### LINKED ISSUE #191: LabelValuesByName incorrect value
I am using LabelValuesByName in my query . The issue i am facing is when i try to get pod value from it , it is returning me an array instead of string with all the pods name 

Expected 
<<index .LabelValuesByName "pod_name">> 
"pod1|pod2"

Got :
[pod1 pod2]

### PR DESCRIPTION
**Pull request by s-urbaniak**
According to documentation LabelValuesByName is supposed to render "|" separated values.
Currently it is returned as a slice per label name. This fixes it

Fixes #191

@paulfantom: as discussed, let's add unit tests for the external metrics rendering too.

### CODE REVIEW

File: pkg/naming/metrics_query_test.go [hunk 1]
```diff
@@ -232,3 +234,121 @@ func TestBuildSelector(t *testing.T) {
...
+		},
+		{
+			name: "multiple LabelMatchers value",
+
+			mq:             mustNewQuery(`<<.LabelMatchers>>`, false),
+			metricSelector: labels.NewSelector().Add(*singleReq, *singleReqMultVals),
+
+			check: checks(
+				hasError(nil),
+				hasSelector("foo=\"bar\",foo=~\"bar|baz\""),
```
Comment (s-urbaniak) [inline pkg/naming/metrics_query_test.go]: nit use backticks for better readability:
```
`foo="bar",foo=~"bar|baz"`
```

File: pkg/naming/metrics_query_test.go [hunk 2]
```diff
@@ -232,3 +234,121 @@ func TestBuildSelector(t *testing.T) {
...
+		},
+		{
+			name: "single LabelMatchers value",
+
+			mq:             mustNewQuery(`<<.LabelMatchers>>`, false),
+			metricSelector: labels.NewSelector().Add(*singleReq),
+
+			check: checks(
+				hasError(nil),
+				hasSelector("foo=\"bar\""),
```
Comment (s-urbaniak) [inline pkg/naming/metrics_query_test.go]: nit: use backticks for better readabilty (see below)

File: pkg/naming/metrics_query_test.go [hunk 3]
```diff
@@ -0,0 +1,354 @@
...
+			check: checks(
+				hasError(nil),
+				hasSelector("map[foo:bar]"),
+			),
+		},
+		{
+			name: "multiple LabelValuesByName",
+
+			mq:             mustNewQuery(`<<.LabelValuesByName>>`, false),
+			metricSelector: labels.NewSelector().Add(*singleReq, *singleReqMultVals),
```
Comment (s-urbaniak) [inline pkg/naming/metrics_query_test.go]: as discussed, let's wrap this to have a bit cleaner code here :-)

File: pkg/naming/metrics_query_test.go [hunk 4]
```diff
@@ -0,0 +1,354 @@
...
+
+			check: checks(
+				hasError(nil),
+				hasSelector("map[foo:bar|baz]"),
```
Comment (s-urbaniak) [inline pkg/naming/metrics_query_test.go]: just to avoid confusion: you are adding two metric selectors here using the same key `"foo"`. Wouldn't it be better to have two separate keys so they appear separately in the map?
